---
- name: Download Packer files.
  get_url:
    dest: "{{ doctl_download_dir }}/{{ item|basename }}"
    url: "{{ item }}"
  with_items:
    - "{{ doctl_zip_url }}"
    - "{{ doctl_checksum_url }}"
    - "{{ doctl_signature_url|default(omit) }}"

- include: gpg.yml
  # Skip by default, since no signatures exist.
  when: doctl_signature_url is defined and doctl_signature_url

- name: Verify checksums.
  command: >
    sha256sum --check --status --ignore-missing
    "{{ doctl_checksum_url|basename }}"
  changed_when: false
  args:
    chdir: "{{ doctl_download_dir }}"

- name: Check Doctl version.
  command: doctl version
  ignore_errors: yes
  changed_when: false
  register: doctl_version_result

- name: Extract Doctl binary files.
  unarchive:
    remote_src: yes
    src: "{{ doctl_download_dir }}/{{ doctl_zip_url|basename }}"
    dest: /usr/local/bin
  when: "doctl_version_result.stdout|default('') != 'Doctl v'+doctl_version"
