---
- name: Download Packer files.
  get_url:
    dest: "{{ doctl_download_dir }}/{{ item|basename }}"
    url: "{{ item }}"
  with_items:
    - "{{ doctl_zip_url }}"
    - "{{ doctl_checksum_url }}"
    - "{{ doctl_signature_url }}"

- name: Fetch Hashicorp GPG key.
  command: gpg --recv-key "91A6E7F85D05C65630BEF18951852D87348FFC4C"
  register: doctl_gpg_key_result
  changed_when: "'unchanged: 1' not in doctl_gpg_key_result.stderr"

- name: Validate GPG signature on checksum file.
  command: >
    gpg --verify
    "{{ doctl_download_dir }}/{{ doctl_signature_url|basename }}"
    "{{ doctl_download_dir }}/{{ doctl_checksum_url|basename }}"
  register: doctl_gpg_key_result
  changed_when: false

- name: Verify checksums.
  command: >
    sha256sum --check --status --ignore-missing
    "{{ doctl_checksum_url|basename }}"
  changed_when: false
  args:
    chdir: "{{ doctl_download_dir }}"

- name: Check Packer version.
  command: packer version
  ignore_errors: yes
  changed_when: false
  register: doctl_version_result

- name: Extract Packer binary files.
  unarchive:
    remote_src: yes
    src: "{{ doctl_download_dir }}/{{ doctl_zip_url|basename }}"
    dest: /usr/local/bin
  when: "doctl_version_result.stdout|default('') != 'Packer v'+doctl_version"
